### ISSUE TITLE
API example incorrect

### ISSUE THREAD

**Issue by yalet** [Mermade/shins#10]
The example in the README for using the API is incorrect. 
In particular, 
`var shins = require('shins');`

does not include the renderer. I think this is because the file declared as 'main' in the package.json is not index.js, but arapaho.js. 

I'm not sure what the actual intention is regarding which module should be main so I'm logging this against the documentation.

**Comment by MikeRalphson** [comment]
'main' being `arapaho.js` was only required for heroku deploys, but `arapaho.js` is already specified in the `Procfile`.

I've updated it to `index.js` as per the documentation.

Many thanks!
