### ISSUE TITLE
Missing include for minify flag

### ISSUE THREAD

**Issue by pglezen** [Mermade/shins#103]
When I try to create a minified build, I receive a message that

```
source/javascripts/all_nosearch.bundle.inc not found
```

The `source/javascripts` directory has 

* `all_nosearch.inc`
* `all.bundle.inc`

but not `all_nosearch.bundle.inc`.  Is this something we should create ourselves?

**Comment by MikeRalphson** [comment]
No, it's bug. As a workaround you should be able to copy `all.bundle.inc` to `all_nosearch.bundle.inc`

**Comment by pglezen** [comment]
Thanks, Mike.  The workaround worked for me.

**Comment by MikeRalphson** [comment]
Please continue the discussion over on [slant](https://github.com/mermade/slant) if still an issue (slant uses a different build system).
