### ISSUE TITLE
The --minify option fails due to missing shins.js

### ISSUE THREAD

**Issue by pseudobjorn** [Mermade/shins#15]
Having installed the latest npm module (2.0.1-3), using the --minify option from the commandline throws an error. I think the error was there before too, but I worked around it then. I am choosing to report it this time.

This is the output from my console:

> { Error: C:\Source\Repos\Testing\node_modules\shins\source\layouts\layout.ejs:31
>     29|     <%- stylesheet_link_tag(current_page.data.highlight_theme||'darkula','screen') %>
>     30|     <% if (current_page.data.search) {%>
>  >> 31|       <%- javascript_include_tag("all") %>
>     32|     <% } else { %>
>     33|       <%- javascript_include_tag("all_nosearch") %>
>     34|     <% } %>
> 
> ENOENT: no such file or directory, open 'C:\Source\Repos\Testing\node_modules\shins\pub\js\shins.js'
>     at Error (native)
>     at Object.fs.openSync (fs.js:642:18)
>     at Object.fs.writeFileSync (fs.js:1348:33)
>     at Object.javascript_include_tag (C:\Source\Repos\Testing\node_modules\shins\index.js:58:16)
>     at eval (eval at compile (C:\Source\Repos\Testing\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:30:17)
>     at returnedFn (C:\Source\Repos\Testing\node_modules\ejs\lib\ejs.js:580:17)
>     at tryHandleCache (C:\Source\Repos\Testing\node_modules\ejs\lib\ejs.js:223:34)
>     at Object.exports.renderFile (C:\Source\Repos\Testing\node_modules\ejs\lib\ejs.js:437:10)
>     at C:\Source\Repos\Testing\node_modules\shins\index.js:212:13
>     at Object.render (C:\Source\Repos\Testing\node_modules\shins\index.js:132:28)
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'C:\\Source\\Repos\\Testing\\node_modules\\shins\\source\\layouts\\layout.ejs' }
> 

It seems to be expecting `shins.js` to exist under `\pub\js`, which it doesn't. Rather,` shins.js` exists in the root-folder of the repo. 

I can work around this issue by adding `\pub\js\shins.js` to the `\shins`-folder under `\node_modules`, so it is not a critical bug, but would be nice if it was fixed.

**Comment by MikeRalphson** [comment]
Have you installed shins as a global module, or are you invoking it from within the `node_modules` directory of your project?

**Comment by MikeRalphson** [comment]
I've published v2.0.1-4 which should ensure the `/pub/js` directory is always present so the minified `shins.js` bundle (which is different from the `shins.js` command-line script) can always be created.

**Comment by pseudobjorn** [comment]
I have not installed shins globally. It exists under the `node_modules` directory of my project. 

Your fix did the trick, although a little 'hacky' imo. I am nitpicking, but rather than providing a `dummy.js` file to ensure that the `/pub/js` folder exists, I think the script itself should ensure that the folder exists, when it needs to write to it. But it is a minor implementation detail, and since your solution works, I will close the issue :)

**Comment by MikeRalphson** [comment]
True, will bear in mind for a clean-up. Thanks.
