### ISSUE TITLE
The option to inline resources (--inline) does not include custom css

### ISSUE THREAD

**Issue by pseudobjorn** [Mermade/shins#16]
If I only specify the --customcss option, relative links to the custom stylesheets (such as `pub\css\theme_overrides.css`) are included in the generated `index.html`-file. This is as expected.

However, when using the --inline option together with the --customcss option, the custom styles in `theme_overrides.css` are not included (I have not checked the other custom stylesheets, but expect the same to be true for them).

I have placed my custom `theme_overrides.css`-file in the `\pub\css`-folder under the `\node_modules\shins`-folder, since that is where I expect shins to be looking for them when I use the --inline option, but that doesn't help. My custom styles are not included.

Is this a bug, or is it intentional?

I do see that **some** styles are included, but I think these are only the standard styles.

PS: 
I also see that the included styles take up a lot of space, as they include comments and whitespace etc.  The included CSS should be minified. Several modules exist that can do this.

**Comment by MikeRalphson** [comment]
Re: your last point, the `.css` files can be rebuilt from the source `.scss` files using the included `buildStyle.js` script. This can produce `.css` in either `nested`, `expanded`, `compact` or `compressed` formats. For ease of merging, I'd prefer to keep the `.css` files in the repo un-minified.

I'll take a look at the interaction between `--customcss` and the new `--inline` option.

**Comment by MikeRalphson** [comment]
Should be fixed in v2.0.1-5. Please re-open the issue if not.
