### ISSUE TITLE
No TOC generated for sections in includes

### ISSUE THREAD

**Issue by pandarrr** [Mermade/shins#18]
There are no Table of Contents entries generated for any sections in include files. I don't have time to submit a fix myself, but located two issues with the layout.ejs.
* The include files get rendered after the TOC is rendered.
* The TOC only uses `page_content` which does not contain the includes content anyway.

**Comment by MikeRalphson** [comment]
Thanks @pandarrr for the bug report and additional digging.

This should be fixed in v2.1.1-1

This release also includes markdown sanitisation by default, but if this causes any problem with HTML embedded in your markdown, you can use the `--unsafe` option to restore the old behaviour.

**Comment by MikeRalphson** [comment]
Please chase if the fix is not working for you.
