### ISSUE TITLE
Can you include external snippets (like in this example) ?

### ISSUE THREAD

**Issue by ghost** [Mermade/shins#20]
Hi,

I want to replicate what is done with spring restdocs, where they generate snippets of documentation based on the tests in the code, and include those snippets in slate documentation. See an example here: https://github.com/spring-projects/spring-restdocs/blob/v1.1.2.RELEASE/samples/rest-notes-slate/slate/source/api-guide.md.erb

Would it be possible to include external snippets like what is done there with `<%= ERB.new(File.read`) %> using shins?

**Comment by ghost** [comment]
Not looking for ruby support btw. Just looking for a way to have one document that can include snippets from elsewhere.

**Comment by MikeRalphson** [comment]
Yes, I think it should be possible, either in a similar way (allowing a html.md.ejs extension for embedded Javascript) or by supporting a markdown pre-processor - such as [markdown-pp-js](https://github.com/MikeRalphson/markdown-pp-js) which supports a `!INCLUDE` directive.

**Comment by ghost** [comment]
asciidoc could be nice (http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#include-files), but I'll leave that entirely up to you :)

**Comment by MikeRalphson** [comment]
Both `include::filename[]` and `!INCLUDE filename` syntaxes are supported in shins v2.1.1-2.

This currently only works for local files, not urls. The `html.md.ejs` option is also not supported yet.

Thanks for the suggestion!
