### ISSUE TITLE
Serving via arapaho doesn't check for changes in includes

### ISSUE THREAD

**Issue by brianreeve** [Mermade/shins#23]
While authoring documentation, it is convenient to serve using the included arapaho.js. However, arapaho doesn't pick up changes to files in the `source/includes` directory.

The workaround is to modify `source/index.html.md` or delete `index.html`, but this is not an ideal workflow.

I see two possible solutions:

1. Modify the behavior of `arapaho.js` such that it rebuilds the html on every request in a temp directory, then serves it from there. (Arguably, anything destructive to the `index.html` at the project's root should be done explicitly anyway.)
2. If any one of `source/index.html.md` or files inside `source/includes/` has modified since `index.html` was modified, rebuild `index.html`.

My preference is the former, but I understand this may be a breaking change if folks are serving docs in production using `arapaho.js`. Maybe a good compromise would be to specify a switch or argument when invoking arapaho to specify you want to always rebuild and serve the temp index.html.

Thoughts on this?

**Comment by MikeRalphson** [comment]
Thanks for raising this. I doubt if anyone is using arapaho as a production web-server (it's not designed for that certainly). 

I think watching the `source/include` directory would be safe default behaviour, and building to a temp file/directory would be a useful additional feature. 

Thanks again for the suggestion.

**Comment by brianreeve** [comment]
Great!

I agree with your assessment and proposed approach.

**Comment by MikeRalphson** [comment]
Changes in v2.2.1-0

* `arapaho` now watches the `source/includes` directory
* the new `--preserve` or `-p` option to `arapaho` preserves the output `.html` file (re-renders are done to a string in memory, so no temporary file/directory was required)
* `tiny-opts-parser` used for options parsing

Thanks again for the suggestions.

**Comment by brianreeve** [comment]
Love it. Thanks!

**Comment by MikeRalphson** [comment]
v2.2.1-1 contains a small additional fix for the case where you're working on more than one source `.md` file at the same time.
