### ISSUE TITLE
[Question] How to build the website for on premise hosting

### ISSUE THREAD

**Issue by SynergiAios** [Mermade/shins#24]
It is for sure a stupid question, as everyone will think, how can you not know that. But to be fair, I don't know much about javascript and all the new frameworks and cool stuff. I was able to write my documentation and preview it with the arapaho webserver. Awesome. But how to build the website now into a static resource, so I can pack this documentation with my framework?

I checked the CLI make-shiv, but wasn't able to get it to run, it always throw me a error. 

So my question is now how to get a rendered static version of the documentation?

**Comment by MikeRalphson** [comment]
Hi @SynergiAios there's no such thing as a stupid question, only insufficient documentation!

If you use the option `--minify` to `shins`, the only things you need to take to your web host is the generated `index.html` and the contents of the `pub` directory, which should be kept relative to it, so the structure is always:

```
{whatever}/index.html
{whatever}/pub/css/
{whatever}/pub/js/
```
If you use the `--inline` option to `shins`, then everything is bundled into the `index.html` file and no `pub` directory is required.

I can definitely improve the `README.md` in this area I think, so thanks for pointing it out.

**Comment by SynergiAios** [comment]
Wow that is awesome thx.

**Comment by SynergiAios** [comment]
Now the declarration in the documentation is really clear and nice to understand. Good job, thx

**Comment by fdanielsen** [comment]
Hi,

I don't want to create a new issue in case it's just my blindness here… But I don't see how the documentation about `--minify` is correct. Even after using that, there's still references to `source/images/navbar.png` for example, and without providing a custom logo URL the default logo will also be requested from `source/images/logo.png`.

In Slate everything relevant from `source` gets copied to a `build` directory. In Shins this is a bit more confusing as it seems `pub` is meant to contain pre-built resources like CSS and JS, with eg. a separate command to build styles. But images are kept in `source`.

So, how can one simply deploy the `index.html` and `pub` directory then?

It would make sense to me if all original resources are kept in `source`, but then gets copied to `pub` with optional build/compilation if needed/requested (eg. .scss to .css, .js bundled and minified and optionally images compressed).

**Comment by MikeRalphson** [comment]
@fdanielsen please could you create a new issue? It just took me half-an-hour to find this read notification again to see your comment.

**Comment by fdanielsen** [comment]
Certainly, sorry about that.

**Comment by MikeRalphson** [comment]
No problem, just didn't want it to get lost again!
