### ISSUE TITLE
Markdown interpreter makes problem with code blocks

### ISSUE THREAD

**Issue by SynergiAios** [Mermade/shins#25]
C# interfaces are written in the following structure if you work with generics

MethodName<InterfaceName>(...);

And the part in between **< >** these signs is interpreted by the markdown interpreter and thus not shown in the code block. See screenshot and see code

Code

````csharp
class MyEventRegisterer : EventRegisterer
{
    public override void RegisterEvents()
    {
        Register<InputTrigger>();
        Register<ClientConnecting>();
        Register<ClientConnected>();
        Register<ConnectedToNetwork>();
        Register<ConnectionEstablished>();
        Register<ClientDisconnected>();
        Register<RequestClientList>();
        Register<ResponseClientList>();
        Register<SnapShotGenerated>();
        Register<SnapShotDeltaGenerated>();
        Register<GameObjectSpawned>();
        Register<GameObjectDestroyed>();
        Register<GameObjectDisabled>();
        Register<GameObjectEnabled>();
        Register<NewInterpolationSpan>();
        Register<RequestSpawnGameObject>();
        Register<RequestDestroyGameObject>();
        Register<RequestEnableGameObject>();
        Register<RequestDisableGameObject>();
    }
}
````

And how it is displayed in shins

![screenshot_2](https://user-images.githubusercontent.com/10873296/36641683-34e71974-1a34-11e8-93ef-370ec3e2696b.png)

**Comment by MikeRalphson** [comment]
It's probably the html sanitisation rather than the markdown renderer itself.

Can you try with the `--unsafe` option to shins (which is fine if you trust the input not to contain any malicious `<script>` tags or anything like that) and see if that fixes it?

**Comment by SynergiAios** [comment]
Yes --unsafe fixed it.

![screenshot_3](https://user-images.githubusercontent.com/10873296/36642123-db8cdb32-1a3a-11e8-9c1a-19d6bc5c84fc.png)

So thx I know how to use this framework now properly x)

**Comment by MikeRalphson** [comment]
Glad that fixed it for you. Don't hesitate if you have any further questions or suggestions.
