### ISSUE TITLE
Inline build is missing slate font data

### ISSUE THREAD

**Issue by SynergiAios** [Mermade/shins#26]
When building with --inline, there is no sideloaded font for slate.ttf, wf, ... These are referenced back to the source folder. So maybe a) upload the font somewhere and sideload it in the html file, b) use a generic font that is present on all systems (looks ugly) or c) use a already well used font like googles robo or whatever and sideload this font.

**Comment by MikeRalphson** [comment]
Yes, this was noted as a limitation in the PR which added the `--inline` option (#13).

Will look at the options you have suggested.

**Comment by SynergiAios** [comment]
Any progress or decision on the font issue when using --inline?

**Comment by MikeRalphson** [comment]
Not as yet. PRs welcome. One option is to use the github repo as a source.

**Comment by MikeRalphson** [comment]
In progress, `--fonturl` option will be present in the next release. Re: your "looks ugly" comment, note that the slate font only includes the search (magnifying-glass) and warning icons. If you want to specify a different font family, this can be done with the `customcss` option.

**Comment by SynergiAios** [comment]
Wow that is awesome. Thx dude. You are the best. I'll wait for it and test and then close the issue.

**Comment by MikeRalphson** [comment]
Thanks for the offer of testing - the new option is included in v2.2.1-2

**Comment by SynergiAios** [comment]
Sorry I'm currently totally out of time. I will test it for sure in the near future, but currently I'm out of time.

**Comment by MikeRalphson** [comment]
No problem, thanks for letting me know.

**Comment by MikeRalphson** [comment]
Please chase if not fixed.
