### ISSUE TITLE
Arbitrary CSS and Logo Paths

### ISSUE THREAD

**Issue by ischeinkman** [Mermade/shins#27]
Currently the only way to include a custom logo and styling is to directly edit ```source/images/logo.png``` and ```pub/css``` directly. This means that every time an update is pushed the custom css and logo must be replaced again and again. To fix this it would make sense to add a pair of command line arguments such as ```--csspath [path/to/folder/] ``` and ```logopath [path/to/file.png]``` that allow the user to pass arbitrary paths to their custom css folders and logo file.

**Comment by MikeRalphson** [comment]
Custom css can be included in `screen_overrides.css` etc which will (rarely, if ever) change, so if you are doing a `git pull` into your fork, they shouldn't conflict. And the logo also won't change.

That said, both additional options sound like good enhancements. PR's would be very welcome!

**Comment by MikeRalphson** [comment]
`--logo`   **specify path to custom logo file** option added in v2.2.1-2

**Comment by MikeRalphson** [comment]
Was included in `v2.2.1-6`
