### ISSUE TITLE
Customising the output path

### ISSUE THREAD

**Issue by simondean** [Mermade/shins#31]
Hi. I’m using shins as an NPM dependency rather than having a copy of all the files in the shins repo. It’s working really well but one limitation I’ve hit is not being able to override the output path of `./index.html` in `./shins.js`. Would it be possible to make the output path configurable like it is in widdershins? Thanks

**Comment by MikeRalphson** [comment]
Are you calling the `shins.js` CLI wrapper or using the `render` function with a callback direct from the main `index.js` ?

Either way, it's a good enhancement. Give me a few mins...

**Comment by MikeRalphson** [comment]
`-o` / `--output` supported in v2.2.1-3

**Comment by simondean** [comment]
I’m using a script in my package.json file to call widdershins and shins:

```
{
  "scripts": {
    "build": "widdershins --environment widdershins.yaml openapi.yaml -o build/slate-markdown/index.html.md && shins build/slate-markdown/index.html.md --customisecss"
  },
  "devDependencies": {
    "shins": "...",
    "widdershins": "..."
  }
}
```

**Comment by simondean** [comment]
Thanks for the enhancement. Would it be possible to pushlish the new version to npmjs.com?

**Comment by MikeRalphson** [comment]
Apologies, I managed to do everything apart from actually publish it. Now done.

**Comment by simondean** [comment]
No worries. I’ve just tried the latest version and the `-o` arg is working successfully for me

**Comment by MikeRalphson** [comment]
Many thanks for confirming.
