### ISSUE TITLE
[INFO] CLI package using shins/widdershins

### ISSUE THREAD

**Issue by tobilg** [Mermade/shins#34]
Thanks for your great work on Shins/Widdershins! I created a CLI which streamlines the usage either on the command line or for using in npm run tasks:

https://github.com/tobilg/api2html

**Comment by MikeRalphson** [comment]
Thanks, yes I saw a tweet about it. Looks good. Would you like to raise a PR to add a link to the README?

**Comment by tobilg** [comment]
Sure, will do! Thanks again!
