### ISSUE TITLE
[Request] Allow override for layout.ejs

### ISSUE THREAD

**Issue by braco** [Mermade/shins#40]
This would be handy for more customized output, I was surprised this wasn't possible.

It might also be worth building the body separately from the rest of the HTML so it can fit as-is into a another HTML shell.

Great package, thanks for your work!

**Comment by MikeRalphson** [comment]
Good thoughts, thanks.

**Comment by MikeRalphson** [comment]
New `--layout` option in `shins@2.3.2-2`. This would allow you to do your second point. I've not included such a template for maintenance / ongoing compatibility with Slate reasons.
