### ISSUE TITLE
Make includes resolve relative to the file with the include line

### ISSUE THREAD

**Issue by woutervh-** [Mermade/shins#42]
Example:

index.md
```
Top
!INCLUDE path/index.md
```

path/index.md
```
Middle
!INCLUDE to/index.md
```

path/to/index.md
```
Bottom
```

Currently this gives an error:
```
shins: included file ./to/index.md not found
```
Because files are always included relative to the first source file:
https://github.com/Mermade/shins/blob/9faac0f1811d4bb4eb29245046ec796dd80a506a/index.js#L158

Would it be possible to include relative from the file that is including the file?

**Comment by MikeRalphson** [comment]
Doable. Would probably need to make including files a recursive process rather than just splicing the content in as-now.

**Comment by MikeRalphson** [comment]
Please continue the discussion over on [slant](https://github.com/mermade/slant) if still an issue.
