### ISSUE TITLE
TradeGecko theme

### ISSUE THREAD

**Issue by P1llus** [Mermade/shins#45]
Hey!

Thanks a lot for porting this over to node, makes it a lot easier for me to utilize it.

In the documentation it mentions that there is an alternate theme provided by TradeGecko, but how would i be able to access this specific theme? As it is not a part of the highlighter module.

The only references i found was for highlight_theme, but there is no tradegecko value available there either.

Is this in any way related to https://developer.tradegecko.com/docs.html and https://github.com/tradegecko/smaug ?

**Comment by MikeRalphson** [comment]
Hi, glad this project is useful to you.

I probably need to make it clearer in the README that the tradegecko theme is an alternative to the default Slate theme (or CSS) and not a syntax highlighting theme.

From memory, all that is required is to include the tradegecko.min.css file after the slate.css on your site.

And yes, it is related to the sites you mention, though it may not necessarily be as up-to-date as those.

**Comment by MikeRalphson** [comment]
https://github.com/Mermade/shins/blob/master/pub/css/tradegecko.min.css can be included with the --css option.  (Edited to correct option name.)

**Comment by P1llus** [comment]
Ah thank you!

Was already using the customcss option as well, will see if i can get that included now 👍 

EDIT: I do agree though that the documentation should just include 2-3 words about how to enable it.

Their newest theme looks pretty good, though they do so much with the formatting etc, which i rather live without.

**Comment by MikeRalphson** [comment]
`README.md` updated, thanks this will probably help others too.

**Comment by ryanlichwalla** [comment]
hey all - just to be clear, how do you get the tradegecko theme to work?  Something like the following?

node shins.js --customcss pub/css/tradegecko.min.css -o index.html
node shins.js --customcss -o index.html

I'm probably doing something as it doesn't seem to work.

**Comment by MikeRalphson** [comment]
Due to the history of when the options were added, the naming is a little misleading.

`--customcss` includes the `pub/css/screen_overrides.css` and `pub/css/print_overrides.css` files.

`--css {css-file}` is used to specify additional CSS files to include.

So `node shins --css pub/css/tradegecko.min.css` should work (just tested here).

As well as this issue being wrong (multiple times!) the `README` was also incorrect, so that's been fixed. Thank you for pointing it out!

**Comment by ryanlichwalla** [comment]
Thanks, Mike.  It looks great now.

I did notice that TOC doesn't have the same style as the tradegecko api - is this just a consequence of using an outdated file or is the TOC not included?

**Comment by MikeRalphson** [comment]
It's possible, as you say, because the Tradegecko theme file I added pre-dates / doesn't include changes necessary for the newer Slate 2.x ToC. Do you see any CSS issues in the browser console?

**Comment by ryanlichwalla** [comment]
Thanks for getting back.

I do see a few issues in the console but I don't think they'd cause this issue:

GET file://fonts.googleapis.com/css?family=Open+Sans:400,600,700 net::ERR_FILE_NOT_FOUND

GET file:///Users/<user>/shins/pub/fonts/slate.woff2?-syv14m net::ERR_FILE_NOT_FOUND

GET file:///Users/<user>/shins/pub/fonts/slate.ttf?-syv14m net::ERR_FILE_NOT_FOUND
