### ISSUE TITLE
Injecting API key dynamically

### ISSUE THREAD

**Issue by aroach** [Mermade/shins#53]
Once a user is logged into our site, I'd like to be able to inject a user's API key dynamically into the API calls within the documentation.  I'm using Widdershins to generate the base docs from OpenAPISpec, and wondering if I would need to add a div/id into the generated Markdown, and then have some custom JS in Shins to accomplish this.  

Has anyone achieved a scenario like this?

**Comment by MikeRalphson** [comment]
I don't know of anyone already implementing this, but done how you suggest, it should be pretty easy.

**Comment by aroach** [comment]
Ok cool @MikeRalphson I'll add a ticket/question in Widdershins, since that seems to be where the "major" work would need to be done.
