### ISSUE TITLE
`includes` functionality broken?

### ISSUE THREAD

**Issue by maximindsl** [Mermade/shins#54]
Hi there,
https://github.com/Mermade/shins/wiki/Using-Includes functionality is broken?

If I try, shins will look for `_api/databases.md` not `api/_databases.md`

Any help on how to use this? 

Thanks,
Max

**Comment by maximindsl** [comment]
Sorry, was looking in the outdated wiki!

https://github.com/Mermade/shins/blob/master/docs/include.md was having the information.

Closing this issue.

**Comment by MikeRalphson** [comment]
I think this is actually a bug in respect of compatibility with Slate (the wikis still match).
