### ISSUE TITLE
Rendering problem with nested attributes

### ISSUE THREAD

**Issue by EitZei** [Mermade/shins#56]
The nested attributes in the following OpenAPI spec renders incorrectly in the HTML.

Command used was `api2html -o index.html .\api.yaml`

In the `TestNOK` the attribute `bar` is renders `» bar` indicating that it would be nested although it is on the top level. I assume that this is because the "previous" attribute is nested two levels.

In the example `TestOK` an additional property is added with nesting at level 1. This fixes the rendering of the top level attribute `bar`.

It should be noted that the JSON examples are rendered correctly and this only affects the description if the schema.

**Screenshot:**

![screenshot](https://user-images.githubusercontent.com/162870/52109063-d19d9180-2604-11e9-839e-74b65c0080eb.png)

**OpenAPI spec:**

```
openapi: 3.0.0

info:
  title: Test
  version: 0.0.0

paths:
  /nok:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestNOK'
      responses:
        '200':
          description: OK
  /ok:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestOK'
      responses:
        '200':
          description: OK          
          
components:
  schemas:
    TestNOK:
      type: object
      properties:
        foo:
          type: object
          properties:
            foofoo:
              type: string
              example: "foofoo"
            foobar:
              type: object
              properties:
                foobarfoo:
                  type: string
                  example: "foobarfoo"
        bar:
          type: string
          example: "Bar"
    TestOK:
      type: object
      properties:
        foo:
          type: object
          properties:
            foofoo:
              type: string
              example: "foofoo"
            foobar:
              type: object
              properties:
                foobarfoo:
                  type: string
                  example: "foobarfoo"
            foozap:
              type: string
              example: "foozap"
        bar:
          type: string
          example: "Bar"
```

**Comment by MikeRalphson** [comment]
Thanks for the detailed report. This looks to be related to https://github.com/Mermade/widdershins/pull/154

**Comment by lrobledo** [comment]
I'm having the same issue. I've been looking through common.js trying to better understand the schemaToArray function.
Do you have any idea why the widdershins#154 didn't also fix this issue?

I'd love to help if possible.

**Comment by lrobledo** [comment]
Hi, I could be way off base, but I ended up just deleting this code block (in common.js): 
```
        if (entry.name) {
            if (state.depth > iDepth) {
                oDepth++;
            }
            if (state.depth < iDepth) {
                oDepth--;
                if (oDepth<0) oDepth=0;
            }
            iDepth = state.depth;
        }

        entry.depth = Math.max(oDepth+offset,0);
```

And replaced it with just this: 

```
        entry.depth = Math.max(state.depth+offset,0);
```

And it's solved my problem.

**Comment by MikeRalphson** [comment]
This is a bug in Widdershins, not Shins. Please subscribe to https://github.com/Mermade/widdershins/pull/154 for further information and release details.
