### ISSUE TITLE
How to include files from project dir instead of node_modules

### ISSUE THREAD

**Issue by traviscrist** [Mermade/shins#58]
I'm trying to use this project using the api as its own project but I cannot get it to include files from anywhere out side of the node_modules/shins/source/includes directory. 

If you project structure looks like: 
```
├── index.js
├── node_modules
├── source
│   ├── includes
│   │   ├── errors.md
│   │   └── travis.md
│   └── index.html.md
└── package.json
```

My API Code looks like: 
```javascript
const fs = require('fs')
let shins = require('shins');
const path = require("path");

async function genDocs () {
  options = {};
  options.cli = true; // if true, missing files will trigger an exit(1)
  options.minify = false;
  options.customCss = false;
  options.inline = true;
  options.unsafe = false; // setting to true turns off markdown sanitisation
  options['no-links'] = false; // if true, do not automatically convert links in text to anchor tags
  const fileLocation = 'source'
  options.source = path.resolve(`${fileLocation}`) // used to resolve relative paths for included files
  // options.logo = './my-custom-logo.png';
  options['logo-url'] = 'https://www.example.com';
  const files = await fs.readFileSync(path.resolve(`${fileLocation}/index.html.md`), 'utf8')
  const markdownString = files 
  shins.render(markdownString, options, async (err, html) => {
    await fs.writeFileSync('test.html', html)
  });
}

genDocs()
```

Even though I am specifying the options.source it keeps just looking in 
`node_modules/shins/source/includes` for the included files. Is there any way to get it to look at the project source and not the location of the shins source. I think this is related to #47 which sets the directory to always be `__dirname` but maybe I am just reading the docs wrong. From what I can tell source should let me configure where the includes folder is but it doesn't seem to do anything. 

Am I using source wrong? How is options.source intended to be used? 

Thanks!

**Comment by MikeRalphson** [comment]
As per the comment above, `options.source` is

> // used to resolve relative paths for **included files**

and has no bearing on where the input `source` and `pub` directories are located. 

You should find your issue has been solved by the recent addition of the `--root` option introduced in #59 - please let me know if not.
