### ISSUE TITLE
Support (more) complex "includes" structure

### ISSUE THREAD

**Issue by omallassi** [Mermade/shins#64]
All, 

First of all, thanks for this project. I was trying to run a custom layout and wanted to organise my pages in a different way and have them organised per "domain"

I thus change my layout and index.html.md to have a locals like

     "toc_footers": ["<a href=\"https://www.murex.com\">Copyright & other legal stuff....</a>"],
            "custom": [{
                "name": "domain_name_1",
                "includes": ["api", "api5", "api3", "api4"]
            }, {
                "name": "domain name 2",
                "includes": ["api2"]
            }, {
                "name": "domain name 3",
                "includes": ["api2"]
            }],
            "search": true,
            "highlight_theme": "dracula",
            "headingLevel": 3
        }

What I observe is that the method function preProcess(content,options) { in index.js is called as many times as the number of "name" in the custom attr. 
resulting in the content being in index.html.md being added multiple times. 

What am I missing? 
Is this something (that could be) supported? 
Apologies if I missed something and if this  is already supported. 

thanks

**Comment by MikeRalphson** [comment]
Please continue the discussion over on [slant](https://github.com/mermade/slant) if still an issue.
