### ISSUE TITLE
Unable to create "spacers" in TOC with blank h1s like with Slate

### ISSUE THREAD

**Issue by dustinloflandsmith** [Mermade/shins#66]
Hi @MikeRalphson, could use your help on a nitpicky little issue I'm having.

Using lord/slate, I can include a `_blank.md` file containing only the code 
```html
<h1 id="_"><br> </h1>
```
wherever I need to create a gap between items in the TOC. 

Slate renders this as 
```html
<a href="#_" class="toc-h1 toc-link" data-title=" "><br> </a>
``` 
in the resulting index.html file.

Using the exact same source files in shins doesn't display the same behavior, it renders as 

```html
<a href="#_" class="toc-h1 toc-link" data-title=" "> </a>
```
without the `<br>` and I can't figure out how to get shins to keep it!

**Comment by MikeRalphson** [comment]
From a quick look it shouldn't affect things, but could you check if using the `--unsafe` option to disable html sanitisation helps at all?

**Comment by dustinloflandsmith** [comment]
Just gave it a try and the behavior persists while using `--unsafe`.

**Comment by MikeRalphson** [comment]
Are you able to test latest `master` from github?  If not, don't worry and I'll cut a new release.

**Comment by dustinloflandsmith** [comment]
Just tested on the latest master, with and without `--unsafe` --> the ToC includes the headers now but the `<br>` is included as text.
Also tested with:
- `<h1 id="_">&nbsp</h1>`           --->  everything inside `<h1>` tags appears in ToC as text
- `<h1 id="_"><&nbsp></h1>`              ^ (same as above)
- `<h1 id="_"><pre></pre></h1>`        ^ (same as above)
- `<h1 id="_"><pre> </pre></h1>`       ^ (same as above)
- just a plain space (i.e. `<h1 id="_"> </h1>`)--> nothing appears in the ToC.

**Comment by MikeRalphson** [comment]
Please continue the discussion over on [slant](https://github.com/mermade/slant) if still an issue.
