### ISSUE TITLE
Changes to nested includes are not picked up

### ISSUE THREAD

**Issue by thedeedawg** [Mermade/shins#67]
Hi there,

When using nested includes (includes placed in an subfolder within the `source/includes` folder, as documented on the [wiki](https://github.com/Mermade/shins/wiki/Using-Includes)), changes to them will not be picked up while using the arapaho server locally. As nested includes are a documented feature and will otherwise work, this is clearly an oversight.

It can be solved by changing the watch on the includes folder to be recursive.

Thanks.

**Comment by MikeRalphson** [comment]
Fixed in `shins@2.3.2-5`.
