### ISSUE TITLE
New --root option not supported when building styles

### ISSUE THREAD

**Issue by fdanielsen** [Mermade/shins#70]
The new `--root` option is very handy, in particular when you want to use shins as a standalone builder without the source files directly in the repo. We've created a Docker image that contains the shins source, but mount a separate volume as root which then contains the source and pub directories, which are then the only things in our repo.

But we currently can't use the `buildstyles.js` script, since it doesn't care about `--root` at all.

Also to mention, it would really be nice if the `--root` option changed the output location of `index.html` automatically rather than have to specify that through `--output`, since all references to resources in the generated HTML is relative to root.

**Comment by MikeRalphson** [comment]
Fixed in `shins@2.3.2-5`.
