### ISSUE TITLE
Incomplete build with --minify

### ISSUE THREAD

**Issue by fdanielsen** [Mermade/shins#71]
The documentation for the `--minify` option states that after building the site using it one can deploy a complete version of the site by just uploading the `index.html` file and `pub` directory.

That seems to be incorrect. The build still generates references to particularly images within the `source` directory. These image URLs can't be fixed without patching the layout template. The whole `image_tag` template helper function is hardwired to the `source` directory too.

The ideal situation in my opinion is that the build should compile and copy all resources from `source` to the `pub` directory, and all URLs should reference files in `pub`.

I've currently solved this by creating a custom npm command which both copies images from `source` to `pub`, and compiles all .scss files from `source/stylesheets` to `pub/css` before running the shins build. This also means I can write override styles in .scss files instead of directly editing .css files in `pub`.

I can also note that I think the fonts are also referenced from `source`, not from this GitHub repo as the documentation states by default. Though I've removed the use of this font from our site, so can't confirm that this is correct right now.

**Comment by MikeRalphson** [comment]
Please continue the discussion over on [slant](https://github.com/mermade/slant) if still an issue.
