### ISSUE TITLE
layout option does not resolve to absolute path

### ISSUE THREAD

**Issue by DavidBiesack** [Mermade/shins#73]
I'm running shins via a wrapper Node.js app. In my `options` object, I'm trying to pass an alternate layout file:
```
const options = {
    cli: false, // if true, missing files will trigger an exit(1)
    minify: false,
    customCss: false,
    inline: false,
    layout: `${__dirname}/_docs/apis/source/layouts/jekyll.ejs`
  };
```
and then when I invoke
```
shins.render(source, options, function(err, html) { ... }
```
I get an err
```
Error: ENOENT: no such file or directory, open '/Users/david.biesack/dev/node_modules/shins/Users/david.biesack/dev/_docs/apis/source/layouts/jekyll.ejs'
```

Shins is apparently appending my absolute layout path `/Users/david.biesack/dev/_docs/apis/source/layouts/jekyll.ejs`
to where the shins npm module is inside my `dev` project, `/Users/david.biesack/dev/node_modules/shins`

I cannot store my layout file in `node_modules/shins`.

I suggest shins only look relative to its deployment root if the layout path is relative (does not start with `/` or `./`). This may require changing how the default path is passed.

**Comment by DavidBiesack** [comment]
A workaround is to clone the `source` and `pub` completely and pass in the `root` global option, but I'd prefer to let shins provide most of the defaults and let me just specify overrides such as my own layout.

**Comment by DavidBiesack** [comment]
I contributed a PR, https://github.com/Mermade/shins/pull/74

**Comment by MikeRalphson** [comment]
Thanks - I think I beat you to it with a somewhat smaller change!

**Comment by MikeRalphson** [comment]
Fixed in `shins@2.3.2-5`.

**Comment by DavidBiesack** [comment]
Using `path.resolve`, an absolute path `-l /path/to/my/layout.ejs' works, as does `shins -l source/layouts/layout.ejs` for a file in the shins root, but `-l ./relative/path/to/my/layout.ejs` does not. Needs to be made relative: `-l $PWD/relative/path/to/my/layout.ejs` 
(My patch works with absolute `/...` paths, relative `./...` paths, and root-relative `source/layouts/...` paths.)

**Comment by MikeRalphson** [comment]
Hmm, I think having relative paths work relative to two different locations will be too confusing.
