### ISSUE TITLE
html tags in code samples are not escaped

### ISSUE THREAD

**Issue by lagebaue** [Mermade/shins#83]
E.g. Widdershins generates the following PHP code sample:

```php
<?php

require 'vendor/autoload.php';

$headers = array(
    'Content-Type' => 'application/json',
    'Authorization' => 'Bearer {access-token}',
```
## Actual: 
Shins does not escape html tags in code samples, so everything until the first closing bracket vanishes from the output.

## Expected:
Shins escapes the htmls tags and shows the full code

**Comment by MikeRalphson** [comment]
Believe this is now fixed, new release soon.

**Comment by MikeRalphson** [comment]
Please continue the discussion over on [slant](https://github.com/mermade/slant) if still an issue.
