### ISSUE TITLE
Embedding partials into Markdown files

### ISSUE THREAD

**Issue by truclyle** [Mermade/shins#84]
Is it possible to embed partials into Markdown files? For example, let's say I have two Markdown files containing information on APIs that are pre-release. I want to embed a partial into both files that informs the reader that these APIs are pre-release. Here's what it could look like:

`foods.md`

```markdown
# Food API

<% include partials/prerelease-notice %>

This API allows you to retrieve information on food....
```

`drinks.md`

```markdown
# Drinks API

<% include partials/prerelease-notice %>

This API allows you to retrieve information on drinks...
```

`prerelease-notice.ejs`

```ejs
Notice: this API is in prerelease and is subject to changes. To gain early access, please contact us at ea@team.com
```

**Comment by MikeRalphson** [comment]
From the README:

* Shins additionally supports [AsciiDoc](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#include-files) `include::filename[]` syntax as well as `!INCLUDE filename` from [markdown-pp](https://github.com/MikeRalphson/markdown-pp-js) - this is not supported by Slate. See some [more information about including files](https://github.com/Mermade/shins/blob/master/docs/include.md).

Does that help / work for you?

**Comment by truclyle** [comment]
No, neither of the syntaxes work. Do you have examples with actual file names? Is it `include::prerelease-notice.adoc[]` and `!INCLUDE prerelease-notice.md`? I tried without the file extensions, in both Markdown body and frontmatter not none of the attempts worked.

**Comment by MikeRalphson** [comment]
Please continue the discussion over on [slant](https://github.com/mermade/slant) if still an issue.
