### ISSUE TITLE
Conditional code annotation

### ISSUE THREAD

**Issue by fed239** [Mermade/shins#85]
There was similar issue in slate: https://github.com/slatedocs/slate/issues/72

I liked html hack from the comment https://github.com/slatedocs/slate/issues/72#issuecomment-175244851 but shins seems to strip html classes.

Would you suggest any workaround?

**Comment by MikeRalphson** [comment]
Thanks for the report. I've relaxed the html sanitisation rules to allow `class` and `id` attributes on `blockquote` elements.

v2.4.1-0 has been released with this fix.

**Comment by fed239** [comment]
Thanks a lot!
