### ISSUE TITLE
Javascript fails when markdown input contains titles with {}

### ISSUE THREAD

**Issue by TomiTakussaari** [Mermade/shins#9]
Background: I have swagger (2) JSON, which is converted to Slate format using [widdershins](https://github.com/Mermade/widdershins), and then I try to display it using Shins.

But it seems that if markdown file has headings containing { or }, _toc.js fails with following error in browser, which then renders page somewhat non-usable.

```
_jquery.js:1463 Uncaught Error: Syntax error, unrecognized expression: #account-exists__get_accounts_{id}_exists
    at Function.Sizzle.error (_jquery.js:1463)
    at Sizzle.tokenize (_jquery.js:2120)
    at Sizzle.select (_jquery.js:2541)
    at Function.Sizzle [as find] (_jquery.js:864)
    at jQuery.fn.init.find (_jquery.js:2787)
    at jQuery.fn.init (_jquery.js:2904)
    at jQuery (_jquery.js:75)
    at HTMLAnchorElement.<anonymous> (_toc.js:40)
    at Function.each (_jquery.js:360)
    at jQuery.fn.init.each (_jquery.js:137)
```
(Tested with latest Chrome):

Similar error does not happen when using Slate

Source markdown:

        ## Account.exists__get_accounts_{id}_exists

Shins renders it as:
   
       <a href="#account-exists__get_accounts_{id}_exists" class="toc-h2 toc-link" data-
       title="Account">Account.exists__get_accounts_{id}_exists</a>

Slate renders it as:
       
      <a href="#account-exists_-em-get_accounts-em-id-_exists" class="toc-h2 toc-link" data-
        title="Account">Account.exists_<em>get_accounts</em>{id}_exists</a>

I did not (yet) further investigate what Sizzle tries to do with that string, but I presume those '{}'-characters can cause other problems too, so perhaps they should be converted to something else ?

Slate seems to just rip them out when rendering html.

Example markdown file:
https://gist.githubusercontent.com/TomiTakussaari/8cbfeab272d53e9d07ca44a4c744e9a8/raw/17ed9c0b5290513ea1863d7c045a973173bd6c27/index.html.md

**Comment by MikeRalphson** [comment]
Could you let me know which version (if from npm) or HEAD commit (if from git) you're using?

**Comment by MikeRalphson** [comment]
I had a local commit ready which fixes this issue. Can you let me know if you're using shins from npm or from a git clone? Thanks for the detailed bug report!

**Comment by TomiTakussaari** [comment]
I am using npm

**Comment by MikeRalphson** [comment]
v2.0.1-1 published. Please let me know if it fixes the issue for you.

**Comment by TomiTakussaari** [comment]
That fixes it, thanks!

Also thanks for great libraries, saved me from lot's of Ruby trouble.
