### ISSUE TITLE
Using the same link for several menu items

### ISSUE THREAD

**Issue by piether** [Mermade/shins#90]
Hi,

First of all thank you for making this project. It's really useful for us.

We're running into the problem of having multiple anchors in the generated HTML having the same id, breaking the internal navigation. I know this has been reported already in #17 and closed but since then Slate has added support for it: https://github.com/slatedocs/slate/wiki/Using-the-same-link-for-several-menu-items
As Shins is stated to be a port of Slate I think it would be nice to add this here as well.

I can implement it but I wouldn't know where to start. Is it a matter of changing the templates or is it some kind of post processing step?

Thanks in advance,
Pieter

**Comment by MikeRalphson** [comment]
Thanks for the kind comments, really appreciated. I've added suffixing of the auto-generated header ids in the case of duplicates. Are you able to test this from a GitHub clone, or would you need a new npm release?

**Comment by piether** [comment]
Great! I can test it from a GitHub clone.

**Comment by piether** [comment]
I tested it today. One thing I noticed that while developing using `npm run start`, that ids are getting bumped for no good reason. 

Steps to reproduce:
- start from clean clone
- run `npm run start`
- change something in `source/index.html.md`
- go to browser and refresh

Expected: 
- In html source: `<h1 id="authentication">Authentication</h1>`
Actual:
- In html source: `<h1 id="authentication-2">Authentication</h1>`

If you do another file change it becomes `authentication-3` and so forth. To reset it you need to delete index.html and run `npm run start` again.

**Comment by MikeRalphson** [comment]
OK, obviously the previously seen header cache isn't being cleared. Doh! Will fix.

**Comment by MikeRalphson** [comment]
Should be fixed now.

**Comment by MikeRalphson** [comment]
Included in `v2.5.0`.
