### ISSUE TITLE
Problems with --inline and the logo of the page.

### ISSUE THREAD

**Issue by sergiopg97** [Mermade/shins#92]
Hi, i'm using shins to create the html using --inline but the logo doesnt see, i do it with the default logo of shins and with the default index.html.md but the logo doesnt see. i use this commend for generate the html. **node shins.js --inline** . I don't know if I need to do something else to make it work. Thanks

![05-05-2020 12-31-19](https://user-images.githubusercontent.com/46752317/81057265-60662180-8ecc-11ea-860b-562201e85853.png)

**Comment by MikeRalphson** [comment]
Thanks for reporting this. Will be fixed in the next release.

**Comment by MikeRalphson** [comment]
Fixed in `v2.5.0`.
